### ISSUE TITLE
jquery-oembed-all version.

### ISSUE THREAD

**Issue by ChALkeR** [w8tcha/CKEditor-oEmbed-Plugin#69] opened 2015-02-01 07:33 UTC
The current Readme states:
> This Plugin uses the jquery-oembed-all Plugin located at https://github.com/starfishmod/jquery-oembed-all.

That project is dead. You could use https://github.com/nfl/jquery-oembed-all instead (as suggested by @starfishmod), it has some updates.

If you use your own modified version, you could rebase it and clarify this in the Readme.md.

**Comment by w8tcha** [comment] 2015-02-02 06:17
The problem is i made to many changes, this could be only resolved by manually going thru all the changes

**Comment by boynet** [comment] 2015-02-23 17:47
+1

**Comment by NicoHaase** [comment] 2015-06-02 09:03
So, why not creating a pull request upstream?

**Closed** 2015-08-01 09:11 UTC
